
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
    command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-c", "prisma migrate deploy && prisma db seed && npm run dev"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JFA_MEMBER_URL: ${JFA_MEMBER_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8 --encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: