version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >-
      sh -c "
        prisma migrate deploy &&
        prisma db seed &&
        npm run dev
      "
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8 --encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: