services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    # prisma は npx で、sh -lc でエラー時に即落ちるように
    command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-lc", "npx prisma migrate deploy && npx prisma db seed && npm run dev"]
    environment:
      # ホストに DATABASE_URL があっても、無い場合は db:5432 を使う
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb?schema=public
      JFA_MEMBER_URL: ${JFA_MEMBER_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8 --encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
