import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import AuthProvider from "@/components/AuthProvider";
import CanvasParticles from "@/components/CanvasParticles";
import Analytics from "@/components/Analytics";
import HomeNav from "@/components/HomeNav";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CanvasParticles />
        <AuthProvider>
          <Header />
          <HomeNav isAdmin={session?.user?.isAdmin ?? false} />
          <div className="mt-16">
            <Analytics />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
